# Site settings
title: Ruby for Good
email: info@rubyforgood.org
copyright_name: Ruby for Good
description: > # this means to ignore newlines until "baseurl:"
  Making the world gooder.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RubyforGood
github_username: rubyforgood

# Build settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"

# Plugin configuration settings
# paginate: 5
# paginate_path: "/blog/page:num/"
