# Site settings
title: Ruby for Good
email: info@rubyforgood.org
description: > # this means to ignore newlines until "baseurl:"
  Making the world gooder.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"