# Site settings

title: Ruby for Good
email: info@rubyforgood.org
copyright_name: Ruby for Good
description: > # this means to ignore newlines until "baseurl:"
  Making the world gooder.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# facebook_url: 
twitter_url: https://twitter.com/RubyforGood
github_url: https://github.com/rubyforgood/
# pinterest_url: 
linkedin_url: https://www.linkedin.com/company/ruby-for-good/
# instagram_url: 
twitch_url: https://www.twitch.tv/rubyforgood
classic-logo: "/assets/img/logos/classic-logo.png"
white-logo: "/assets/img/logos/white-logo.png"
special-logo: "/assets/img/logos/special-logo.png"
# mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
# mailchimp_input_name: "b_307862c135e4548eecf86f389_342411fb35"
# TODO: Get MailChimp info

# permalink: "/:title"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

cover_image: "/assets/img/theme-stock/bg/page-title.jpg"


# Collections
collections_dir: all-collections
collections:
  non-profit-partners:
    output: true
    permalink: /:collection/:path
  our-board:
    output: true
    permalink: /:collection/:path
  our-projects:
    output: true
    permalink: /:collection/:path
  our-team:
    output: true
    permalink: /:collection/:path

# Front Matter Defaults
defaults:
  # Blog Post Defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # News Article Defaults
  # - scope:
  #     path: "_posts"
  #     type: posts
  #   values:
  #     layout: post
  #     comments: true
  #     share: true
  # Non-Profit Partners Defaults
  - scope:
      path: "_non-profit-partners"
      type: non-profit-partners
    values:
      layout: page
      comments: false
      share: false
  # Our Board Defaults
  - scope:
      path: "_our-board"
      type: our-board
    values:
      layout: page
      comments: false
      share: false
  # Our Projects Defaults
  - scope:
      path: "_our-projects"
      type: our-projects
    values:
      layout: page
      comments: false
      share: false
  # Our Team Defaults
  - scope:
      path: "_our-team"
      type: our-team
    values:
      layout: page
      comments: false
      share: false


########################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination page
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  permalink: '/pages/blog/:num/' # Pages are simple html file
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional: The title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many paginated pages to create (default: 0, means all)
  limit: 0
  
  # Optional: Defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional: Sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional: The default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional: The default tag to use, omit to disable
  tag: ''

  # Optional: The default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code)
  locale: '' 

 # Optional: Omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional: The default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: 'html'

  # Optional: The default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"