# Site settings
title: Ruby for Good
email: info@rubyforgood.org
copyright_name: Ruby for Good
description: > # this means to ignore newlines until "baseurl:"
  Making the world gooder.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RubyforGood
github_username: rubyforgood

# Build settings
lsi: false
safe: true
source: "/_site/"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugin configuration settings
paginate: 5
paginate_path: "/blog/page:num/"

plugins: [jekyll-paginate, jekyll-feed]